name: Deploy Gradio Chatbot to Hugging Face

on:
  push:
    branches:
      - main  # Deploy on push to main branch
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure Git for Hugging Face
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Deploy to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Clone using authentication
          git clone https://user:${HF_TOKEN}@huggingface.co/spaces/aniloooooo/gradio-ai-chatbot hf-repo
          
          # Copy new files (excluding .git directory)
          rsync -av --exclude='.git' . hf-repo/
          cd hf-repo
          
          # Commit and push changes
          git add .
          git commit -m "Auto-deploy from GitHub Actions" || echo "No changes to commit"
          git push origin main
